### ISSUE TITLE
Django - Tensorflow 호환 문제

### ISSUE THREAD

**Issue by TaeBbong** [ehdgks0627/WALLnut#7]
장고에서 텐서플로우를 import하면 에러가 발생하며 중단합니다..ㅠㅠ
괜히 구글에 관련 프로젝트가 적은게 아니었군요..

**Comment by ehdgks0627** [comment]
7867ada839d974b40aebb30a96be85bedc4c57f2
Django - Keras(CNTK backend) 사용으로 해결
